version: '3.8'

services:
  web:
    image: manish275/reserveflow:latest
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=postgresql://postgres:password123@db:5432/reserveflow?schema=public
      - DIRECT_URL=postgresql://postgres:password123@db:5432/reserveflow?schema=public
      - NEXTAUTH_SECRET=566754545679897sdaert
      - NEXTAUTH_URL=http://localhost:3000
    depends_on:
      - db
    restart: always

  db:
    image: postgres:15-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password123
      - POSTGRES_DB=reserveflow
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always

volumes:
  postgres_data:
